/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ChessCore;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Shada
 */

public class ChessGUI extends JFrame {

    private final ChessGame chessGame;
    private Square selectedSquare;

    public ChessGUI(ChessGame chessGame) {
        this.chessGame = chessGame;
        initializeGUI();
    }

    private void initializeGUI() {
        setTitle("Chess Game");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new GridLayout(8, 8));

        // Create buttons for each square on the chessboard
        for (BoardFile file : BoardFile.values()) {
            for (BoardRank rank : BoardRank.values()) {
                Square square = new Square(file, rank);
                JButton button = createSquareButton(square);
                add(button);
            }
        }

        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private JButton createSquareButton(final Square square) {
        JButton button = new JButton();
        button.setPreferredSize(new Dimension(60, 60));

        

        // Set the piece image on the button
        Piece piece = chessGame.getPieceAtSquare(square);
        if (piece != null) {
            // You need to have images for each piece, implement this part accordingly
            button.setIcon(new ImageIcon(getPieceImage(piece)));
        }

        // Add action listener to handle button clicks
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleSquareClick(square);
            }
        });

        return button;
    }

    private void handleSquareClick(Square square) {
        if (selectedSquare == null) {
            // First click, highlight valid moves
            selectedSquare = square;
            highlightValidMoves(square);
        } else {
            // Second click, make the move
            Move move = new Move(selectedSquare, square);
            if (chessGame.makeMove(move)) {
                updateGUI();
            }
            selectedSquare = null;
        }
    }

    private void highlightValidMoves(Square square) {
        List<Square> validMoves = chessGame.getAllValidMovesFromSquare(square);
        for (Component component : getContentPane().getComponents()) {
            JButton button = (JButton) component;
            Square buttonSquare = getSquareFromButton(button);
            if (validMoves.contains(buttonSquare)) {
                button.setBackground(Color.YELLOW); // Highlight valid moves in yellow
            }
        }
    }

    private void updateGUI() {
        // Update the GUI after each move
        for (Component component : getContentPane().getComponents()) {
            JButton button = (JButton) component;
            Square square = getSquareFromButton(button);
            Piece piece = chessGame.getPieceAtSquare(square);
            if (piece != null) {
                // Update the piece image
                button.setIcon(new ImageIcon(getPieceImage(piece)));
            } else {
                // Clear the button if there is no piece on the square
                button.setIcon(null);
            }
          
        }
        repaint();
    }

    private Square getSquareFromButton(JButton button) {
        // Convert the button's text to a Square object
        // Implementation depends on how you assign buttons to squares
        // Example: button.getText() or store Square in button's client property
        return null;
    }

    private Image getPieceImage(Piece piece) {
        // Implement this method to get the image of the given piece
        // Example: return new ImageIcon("path/to/image.png").getImage();
        return null;
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

